# Enable mouse support (click to resize panes, scroll, etc.)
set -g mouse on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "janoamaral/tokyo-night-tmux"
# Default keybindings
set -g prefix C-b  # Change prefix from Ctrl-b to Ctrl-b (default)
unbind C-b        # Remove default Ctrl-b prefix
bind -n C-b send-prefix  # Rebind Ctrl-b to send prefix

# Navigation
bind -n C-o next-window  # Switch to next window (Ctrl-o)
bind -n C-p previous-window  # Switch to previous window (Ctrl-p)

# Window management
bind w new-window       # Open new window (Ctrl-w)
bind s select-pane      # Select pane (Ctrl-s)
bind d kill-window      # Close window (Ctrl-d)

# Resizing panes
bind -r H resize-pane -L 5  # Move pane left (Ctrl-arrow keys)
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5


# Status bar (show time, host, etc.)
set -g status on
set -g status-position top
set -g status-interval 1
set -g status-left "#[fg=colour15]#H #[fg=colour10]#W#[default]"
set -g status-right "%H:%M %d-%b-%Y"

# Start tmux in a new session on login (optional)
if-shell "test -z $TMUX" "new-session -s main -c ~"


run '~/.tmux/plugins/tpm/tpm'
