#! /bin/sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

wmname LG3D &
/home/array/.config/bspwm/scripts/autostart.sh &
/home/array/.config/bspwm/scripts/launch.sh &
export _JAVA_AWT_WM_NONREPARENTING=1
export LIBVA_DRIVER_NAME=iHD
export XCURSOR_THEME='Bibata-Modern-Ice'
export XCURSOR_SIZE=24
xsetroot -cursor_name Bibata-Modern-Ice
# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 2
bspc config window_gap 5
bspc config top_padding 0
bspc config bottom_padding 0

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color "#bfc9f4"
bspc config normal_border_color "#1a1b26"

