#! /bin/sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

wmname LG3D &
/home/array/.config/bspwm/scripts/autostart.sh &
# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 4
bspc config window_gap 6
bspc config top_padding 0
bspc config bottom_padding 0

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focused_border_color "#bfc9f4"
bspc config normal_border_color "#1a1b26"

