; ===== MAIN BAR SETTINGS =====
[bar/main]
width = 100%
height = 54
radius = 0
line-size = 2
line-color = #cba6f7
override-redirect = false
background = #111117
foreground = #cbd0ec
enable-ipc = true
font-0 = "JetBrainsMono Nerd Font:size=16:weight=SemiBold;3"
font-1 = "DejaVu Sans Mono wifi ramp:size=17;0"
font-2 = "Noto Sans:size=12;1"
font-3 = "JetBrainsMonoNF:size=12;3"
font-4 = "JetBrainsMonoNF:size=19;4"


modules-left   = workspaces  xwindow
modules-center = clock 
modules-right  = tray battery  backlight   alsa  network bluetooth 
separator = "  "
padding-left = 1
padding-right = 3
module-margin = 1.0
wm-restack = bspwm

; ===== CUSTOM MODULES =====

[module/spacer]
type = custom/text
label = 
format-foreground = #373b41
label-font = 4

[module/cpu-governor]
type = custom/script
exec = ~/.config/polybar/profile.sh
interval = 2
click-left = ~/.config/polybar/profile.sh toggle
label = %output%
label-font = 5

[module/logo]
type = custom/text
format = ""
format-foreground = #cbd0ec
label-font = 5



[module/workspaces]
type = internal/bspwm

format = <label-state>
index-sort = true
pin-workspaces = true

label-focused = %index%
label-focused-foreground = #bfc9f4
label-focused-underline = #bfc9f4
label-focused-padding = 1 

label-occupied = %index%
label-occupied-foreground = #6c7086
label-occupied-padding = 1

label-empty = %index%
label-empty-foreground = #414456
label-empty-padding = 1

label-urgent = %index%
label-urgent-foreground = #f38ba8
label-urgent-underline = #f38ba8
label-urgent-padding = 1

;==== SYSTEM MODULES =====
[module/xwindow]
type = internal/xwindow
label = %title:0:30...%
label-foreground = #cbd0ec

[module/memory]
type = internal/memory
interval = 2
label =   %gb_used%
label-foreground = #d2d1d3

[module/cpu]
type = internal/cpu
interval = 2
label =   %percentage%%
label-foreground = #cbd0ec

[module/temperature]
type = internal/temperature
interval = 2
hwmon-path = /sys/class/hwmon/hwmon8/temp1_input
warn-temperature = 75
format = <ramp> <label>
format-warn = <label-warn>
label = %temperature-c%
label-warn =  %temperature-c%
label-warn-foreground = #f38ba8
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-foreground = #d2d1d3

[module/clock]
type = internal/date
interval = 1
date = %a %d
time = %H:%M
label = %date%  %time%
label-foreground = #cbd0ec

[module/tray]
type = internal/tray
tray-spacing = 2px
tray-size = 46%
tray-padding = 2px
tray-foreground = #cbd0ec

[module/alsa]
type = internal/pulseaudio
use-ui-max = true
interval = 5
format-volume = <label-volume>
label-volume =   %percentage%%
label-volume-foreground = #cbd0ec
label-muted = 󰝟 muted
label-muted-foreground = #cbd0ec
click-right = kitty -e wiremix 
label-font = 5

[module/network]
type = internal/network
interface = wlan0
interval = 1.0
accumulate-stats = true
unknown-as-up = true
label-connected = inix
label-disconnected = 
format-connected = <ramp-signal> 
format-disconnected = <label-disconnected>
ramp-signal-0 =  
ramp-signal-1 =  
ramp-signal-2 = 󰤟 
ramp-signal-3 = 󰤢 
ramp-signal-4 = 
ramp-signal-5 = 
click-right = kitty -e nmtui 

[module/backlight]
type = internal/backlight
label = 󰃠  %percentage%%
card = intel_backlight
use-actual-brightness = true
poll-interval = 0
enable-scroll = true
scroll-interval = 2

[module/battery]
type = internal/battery
full-at = 99
battery = BAT0
adapter = ADP1
poll-interval = 1
time-format = %H:%M
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> 100% 
label-charging = %percentage%%
label-discharging = %percentage%%
label-full = " Full"
ramp-capacity-0 = 󰁺
ramp-capacity-1 = 󰁺
ramp-capacity-2 = 󰁻
ramp-capacity-3 = 󰁼
ramp-capacity-4 = 󰁽
ramp-capacity-5 = 󰁾
ramp-capacity-6 = 󰁿
ramp-capacity-7 = 󰂀
ramp-capacity-8 = 󰂁
ramp-capacity-9 = 󰂂
ramp-capacity-10 = 󰁹
animation-charging-0 = 󰢟
animation-charging-1 = 󰢜
animation-charging-2 = 󰂆
animation-charging-3 = 󰂇
animation-charging-4 = 󰂈
animation-charging-5 = 󰢝
animation-charging-6 = 󰂉
animation-charging-7 = 󰢞
animation-charging-8 = 󰂊
animation-charging-9 = 󰂋
animation-charging-10 = 󰂅
animation-charging-framerate = 750

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/bluetooth.sh
interval = 5
click-left = kitty -e bluetuith 
label = %output%
label-font = 5 

[module/bsp-layout]
type = custom/script
exec = ~/.config/polybar/layouts.sh
interval = 1
click-left = ~/.config/polybar/layouts.sh next
click-right = ~/.config/polybar/layouts.sh prev
label = %output%
